#!/usr/bin/env python3
"""Project .cursor/ engine rules and skills into a Claude Code home (.claude/ + CLAUDE.md).

Lexicon's engine is authored once, for Cursor, under `.cursor/`. Claude Code reads a
different layout (`CLAUDE.md` + `.claude/skills/`), so without a projection the engine
is Cursor-only — none of the rules load under Claude Code. This script is the projection:

    .cursor/  ==  SOURCE OF TRUTH  (edit here)
    .claude/ + CLAUDE.md  ==  GENERATED  (never edit — re-run this script)

Mapping (derived, not hand-listed):
  * rule with `alwaysApply: true`        -> a section in CLAUDE.md (always loaded)
  * .cursor/skills/<name>/               -> .claude/skills/<name>/ verbatim
  * rule (alwaysApply: false) whose guidance already exists as skill `lexicon-<rule>`
                                         -> skipped (the skill carries it; the rule is
                                            only Cursor's glob-auto-attach layer)
  * orphan rule (alwaysApply: false, no skill twin)
                                         -> .claude/skills/lexicon-<rule>/ (new skill)

Usage:
  python3 scripts/sync_claude.py            # write the projection
  python3 scripts/sync_claude.py --check    # exit 1 if the projection is stale (for lint/CI)

Stdlib only. Deterministic — same source always yields the same output.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CURSOR_RULES = ROOT / ".cursor" / "rules"
CURSOR_SKILLS = ROOT / ".cursor" / "skills"
CLAUDE_SKILLS = ROOT / ".claude" / "skills"
CLAUDE_MD = ROOT / "CLAUDE.md"

GEN_BANNER = "GENERATED by scripts/sync_claude.py from .cursor/ — do not edit; edit the source and re-run."


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter dict, body). Minimal `key: value` parser — enough for these files."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    fm: dict[str, str] = {}
    for line in parts[1].splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        fm[key.strip()] = val.strip().strip('"')
    return fm, parts[2].lstrip("\n")


def skill_names() -> set[str]:
    if not CURSOR_SKILLS.is_dir():
        return set()
    return {p.name for p in CURSOR_SKILLS.iterdir() if (p / "SKILL.md").is_file()}


def render_skill(name: str, description: str, body: str) -> str:
    desc = description.replace("\n", " ").strip()
    return (
        f"---\nname: {name}\ndescription: {desc}\n---\n\n"
        f"<!-- {GEN_BANNER} -->\n\n{body.rstrip()}\n"
    )


def build() -> dict[pathlib.Path, str]:
    """Compute every generated file's content. Pure — writes nothing."""
    out: dict[pathlib.Path, str] = {}
    skills = skill_names()

    # 1. Existing Cursor skills, copied verbatim (+ a generated marker).
    for name in sorted(skills):
        fm, body = parse_frontmatter((CURSOR_SKILLS / name / "SKILL.md").read_text(encoding="utf-8"))
        out[CLAUDE_SKILLS / name / "SKILL.md"] = render_skill(name, fm.get("description", ""), body)

    # 2. Rules: alwaysApply -> CLAUDE.md; orphan -> new skill; twin -> skip.
    always_sections = []
    for rule_path in sorted(CURSOR_RULES.glob("*.mdc")):
        stem = rule_path.stem
        fm, body = parse_frontmatter(rule_path.read_text(encoding="utf-8"))
        if fm.get("alwaysApply", "false").lower() == "true":
            always_sections.append((stem, fm.get("description", ""), body))
            continue
        twin = f"lexicon-{stem}"
        if twin in skills:
            continue
        out[CLAUDE_SKILLS / twin / "SKILL.md"] = render_skill(twin, fm.get("description", ""), body)

    # 3. CLAUDE.md from the always-on rules.
    lines = [
        "# Lexicon — Claude Code engine",
        "",
        f"<!-- {GEN_BANNER} -->",
        "",
        "Lexicon's engine is authored under `.cursor/` and projected here for Claude Code by",
        "`scripts/sync_claude.py`. Always-on rules live in this file; task guidance lives as",
        "skills under `.claude/skills/` (invoke by description). See `docs/MEMORY_MODEL.md`.",
        "",
    ]
    for stem, desc, body in always_sections:
        lines.append(f"## {stem}")
        if desc:
            lines.append(f"\n_{desc}_\n")
        lines.append("")
        lines.append(body.rstrip())
        lines.append("")
    out[CLAUDE_MD] = "\n".join(lines) + "\n"
    return out


def existing_generated_skill_files() -> set[pathlib.Path]:
    if not CLAUDE_SKILLS.exists():
        return set()
    return set(CLAUDE_SKILLS.rglob("SKILL.md"))


def main(argv: list[str]) -> int:
    check = "--check" in argv
    planned = build()

    # Detect stale files that would be orphaned (source removed but projection lingering).
    stale = existing_generated_skill_files() - set(planned)

    if check:
        drift = [p for p, c in planned.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        drift += list(stale)
        if drift:
            print("STALE Claude projection — run `python3 scripts/sync_claude.py`:", file=sys.stderr)
            for p in sorted(drift):
                print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("Claude projection up to date.")
        return 0

    for p in sorted(stale):
        p.unlink()
    for p, content in planned.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    skills = sorted(p.parent.name for p in planned if p.name == "SKILL.md")
    print(f"Wrote CLAUDE.md + {len(skills)} skills: {', '.join(skills)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
